/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RFIDgui;
import java.io.IOException;

public class RFIDgui extends javax.swing.JFrame {

    /**
     * Creates new form rfid_gui
     */
    public RFIDgui() {
        initComponents();
        detectedTagTable.setColumnSelectionAllowed(false);
        readFromFile(databaseFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editTagWindow = new javax.swing.JFrame();
        editTagPanel = new javax.swing.JPanel();
        idTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        thumbnailDisplay = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exitTagWindow = new javax.swing.JButton();
        viewFullSizeImage = new javax.swing.JButton();
        fullImageWindow = new javax.swing.JFrame();
        fullImageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        detectedTagScrollPanel = new javax.swing.JScrollPane();
        detectedTagTable = new javax.swing.JTable();
        mainExitButton = new javax.swing.JButton();
        scanButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenuQuit = new javax.swing.JMenuItem();

        editTagWindow.setTitle("Edit Tag");
        editTagWindow.setMinimumSize(new java.awt.Dimension(400, 200));
        editTagWindow.setSize(new java.awt.Dimension(800, 445));

        editTagPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("RFID Tag Data"));
        editTagPanel.setPreferredSize(new java.awt.Dimension(500, 125));

        idTextField.setEditable(false);
        idTextField.setText("123456789");

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLabel.setText("id:");

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Name:");

        nameTextField.setEditable(false);
        nameTextField.setText("Sample Tag");

        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descriptionLabel.setText("Description:");

        descriptionTextField.setEditable(false);
        descriptionTextField.setText("Sample description.");

        javax.swing.GroupLayout editTagPanelLayout = new javax.swing.GroupLayout(editTagPanel);
        editTagPanel.setLayout(editTagPanelLayout);
        editTagPanelLayout.setHorizontalGroup(
            editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTagPanelLayout.createSequentialGroup()
                .addGroup(editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editTagPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(editTagPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(editTagPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(thumbnailDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap())
        );
        editTagPanelLayout.setVerticalGroup(
            editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTagPanelLayout.createSequentialGroup()
                .addGroup(editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editTagPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thumbnailDisplay))
                    .addComponent(descriptionTextField))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        exitTagWindow.setText("Exit");
        exitTagWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTagWindowMouseClicked(evt);
            }
        });

        viewFullSizeImage.setText("View Full Size Image");
        viewFullSizeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewFullSizeImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editTagWindowLayout = new javax.swing.GroupLayout(editTagWindow.getContentPane());
        editTagWindow.getContentPane().setLayout(editTagWindowLayout);
        editTagWindowLayout.setHorizontalGroup(
            editTagWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTagWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editTagWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editTagWindowLayout.createSequentialGroup()
                        .addComponent(editTagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editTagWindowLayout.createSequentialGroup()
                        .addComponent(viewFullSizeImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitTagWindow)))
                .addContainerGap())
        );
        editTagWindowLayout.setVerticalGroup(
            editTagWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTagWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editTagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editTagWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitTagWindow)
                    .addComponent(viewFullSizeImage))
                .addContainerGap())
        );

        fullImageWindow.setTitle("RFID Tag Image");
        fullImageWindow.setSize(new java.awt.Dimension(536, 536));

        fullImageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullImageLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fullImageWindowLayout = new javax.swing.GroupLayout(fullImageWindow.getContentPane());
        fullImageWindow.getContentPane().setLayout(fullImageWindowLayout);
        fullImageWindowLayout.setHorizontalGroup(
            fullImageWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullImageWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fullImageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullImageWindowLayout.setVerticalGroup(
            fullImageWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullImageWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fullImageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RFID Utility");
        setMaximumSize(new java.awt.Dimension(800, 480));
        setPreferredSize(new java.awt.Dimension(800, 415));
        setResizable(false);

        detectedTagScrollPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detected Tags:"));

        detectedTagTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tag Number", "Name", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detectedTagTable.setColumnSelectionAllowed(true);
        detectedTagTable.setMinimumSize(new java.awt.Dimension(45, 200));
        detectedTagTable.getTableHeader().setReorderingAllowed(false);
        detectedTagTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detectedTagTableMouseClicked(evt);
            }
        });
        detectedTagScrollPanel.setViewportView(detectedTagTable);
        detectedTagTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (detectedTagTable.getColumnModel().getColumnCount() > 0) {
            detectedTagTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            detectedTagTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detectedTagScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detectedTagScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        mainExitButton.setText("Exit");
        mainExitButton.setMargin(new java.awt.Insets(5, 10, 5, 10));
        mainExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainExitButtonMouseClicked(evt);
            }
        });

        scanButton.setText("Scan");
        scanButton.setMargin(new java.awt.Insets(5, 10, 5, 10));
        scanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanButtonMouseClicked(evt);
            }
        });

        fileMenu.setText("File");

        fileMenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        fileMenuQuit.setText("Quit");
        fileMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuQuitActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuQuit);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainExitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainExitButton)
                    .addComponent(scanButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readFromFile(String filenameIn) {
        org.json.simple.parser.JSONParser parser = new org.json.simple.parser.JSONParser();
        try {
            org.json.simple.JSONObject obj = (org.json.simple.JSONObject) parser.parse(new java.io.FileReader(filenameIn));
            org.json.simple.JSONArray array = (org.json.simple.JSONArray) obj.get("RFID Data List");
            
            java.util.Iterator i = array.iterator();
            
            while (i.hasNext()) {
                org.json.simple.JSONObject innerObj = (org.json.simple.JSONObject) i.next();
                rfidTagDatabase.add(new RFIDdata(innerObj.get("ID Number").toString(), innerObj.get("Name").toString(), innerObj.get("Description").toString()));
            }
            
            System.out.println(array.toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void exitTagWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTagWindowMouseClicked
        this.editTagWindow.setVisible(false);
        this.editTagWindow.dispose();
    }//GEN-LAST:event_exitTagWindowMouseClicked

    private void fileMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuQuitActionPerformed
        exitReader();
    }//GEN-LAST:event_fileMenuQuitActionPerformed

    private void scanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanButtonMouseClicked
        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        
        rfidTagList = new java.util.ArrayList<RFIDdata>();
        
        
//        tagReads = reader.doRead();
//        for (TagReadData tr: tagReads) {
//            RFIDdata current = new RFIDdata(tr.getTag().epcString());
//            if (rfidTagDatabase.contains(current)) {
//                current = rfidTagDatabase.get(rfidTagDatabase.indexOf(current));
//                System.out.println("match");
//            } else {
//                rfidTagDatabase.add(current);
//            }
//            if (!rfidTagList.contains(current)) {
//                rfidTagList.add(current);
//            }
//        }
        
        ////// Troubleshooting
         rfidTagList.add(new RFIDdata());
        //////
        
        updateTagTable();
        
        this.setCursor(java.awt.Cursor.getDefaultCursor());
    }//GEN-LAST:event_scanButtonMouseClicked

    private void updateTagTable() {
        for (int i = 0; i < detectedTagTable.getRowCount(); i++) {
            for(int j = 0; j < detectedTagTable.getColumnCount(); j++) {
                detectedTagTable.setValueAt("", i, j);
            }
         }
        
        //readFromFile(databaseFile);
        
//        ////////// Print Diagnostic Info
//        System.out.println("\n\nUpdate:\n");
//        for (int i = 0; i < this.rfidTagList.size(); i++) {
//            System.out.println(this.rfidTagList.get(i).tagNumber);
//            System.out.println(this.rfidTagList.get(i).objectName);
//            System.out.println(this.rfidTagList.get(i).objectDescription);
//        }
        
        for (int i = 0; i < rfidTagList.size(); i++) {
            detectedTagTable.setValueAt(rfidTagList.get(i).tagNumber, i, 0);
            detectedTagTable.setValueAt(rfidTagList.get(i).objectName, i, 1);
            detectedTagTable.setValueAt(rfidTagList.get(i).objectDescription, i, 2);
        }
    }
    
    
    private void populateTagWindow(RFIDdata currentIn){
        this.editTagWindow.setVisible(true);
        //this.editTagWindow.setSize(946, 442);
        this.idTextField.setText(currentIn.tagNumber);
        this.nameTextField.setText(currentIn.objectName);
        this.descriptionTextField.setText(currentIn.objectDescription);
        try {
            String current = new java.io.File( "." ).getCanonicalPath();
            java.nio.file.Path folderPath = java.nio.file.Paths.get(current, "database", currentIn.tagNumber);
            
            java.io.File file = new java.io.File(folderPath.toString());
            
            java.nio.file.Path filePath;
            
            if (file.exists()) {
                filePath = java.nio.file.Paths.get(folderPath.toString(), "thumb.png");
            } else {
                filePath = java.nio.file.Paths.get(current, "database", "default", "thumb.png");
            }
            
            this.thumbnailDisplay.setIcon(new javax.swing.ImageIcon(filePath.toString()));
            
        } catch (IOException ex) {
            System.out.println("Error resizing the image.");
            ex.printStackTrace();
        }
    }
    
    private void detectedTagTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detectedTagTableMouseClicked
        if (evt.getClickCount() == 2) {
            javax.swing.JTable target = (javax.swing.JTable)evt.getSource();
            int row = target.getSelectedRow();

            RFIDdata current = rfidTagList.get(rfidTagList.indexOf(new RFIDdata(target.getValueAt(row, 0).toString())));
            
            populateTagWindow(current);
        }
    }//GEN-LAST:event_detectedTagTableMouseClicked

    private void createImageData(java.io.File inFile, String inID) {
        try {
            String current = new java.io.File( "." ).getCanonicalPath();
            java.nio.file.Path folderPath = java.nio.file.Paths.get(current, "database", inID);
            java.io.File file = new java.io.File(folderPath.toString());
//            System.out.println("Proposed dir:"+folderPath.toString());
            
            if (!file.exists()) {
                if (!file.mkdir()) {
                   System.out.println("Failed to create directory!");
                }
            }

            ImageResizer imageResizer = new ImageResizer();
            
            java.nio.file.Path mainFilePath = java.nio.file.Paths.get(folderPath.toString(), "main.png");
            java.nio.file.Path thumbFilePath = java.nio.file.Paths.get(folderPath.toString(), "thumb.png");
            
            imageResizer.resize(inFile, mainFilePath.toString(), 1);
            imageResizer.resize(inFile, thumbFilePath.toString(), 200, 200);
        } catch (IOException ex) {
            System.out.println("Error resizing the image.");
            ex.printStackTrace();
        }
    }
    
    private void viewFullSizeImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewFullSizeImageMouseClicked
        
        try {
            String current = new java.io.File( "." ).getCanonicalPath();
            java.nio.file.Path folderPath = java.nio.file.Paths.get(current, "database", this.idTextField.getText());
            java.io.File file = new java.io.File(folderPath.toString());
            java.nio.file.Path filePath;
            if (file.exists()) {
                filePath = java.nio.file.Paths.get(folderPath.toString(), "main.png");
            } else {
                filePath = java.nio.file.Paths.get(current, "database", "default", "main.png");
            }
            javax.swing.ImageIcon newIcon = new javax.swing.ImageIcon(filePath.toString());
            newIcon.getImage().flush();
            newIcon = new javax.swing.ImageIcon(filePath.toString());
            newIcon.getImage().flush();
            java.awt.Dimension pictureDimension = new java.awt.Dimension(newIcon.getIconWidth(), newIcon.getIconHeight());
            java.awt.Dimension windowDimension = new java.awt.Dimension(newIcon.getIconWidth() + 14, newIcon.getIconHeight() + 48);
            System.out.println(pictureDimension.toString());
            this.fullImageLabel.setSize(pictureDimension);
            this.fullImageLabel.setIcon(newIcon);
            this.fullImageLabel.updateUI();
            this.fullImageWindow.setSize(windowDimension);
            this.fullImageWindow.pack();
            this.fullImageWindow.setVisible(true);
            
        } catch (IOException ex) {
            System.out.println("Error finding image.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_viewFullSizeImageMouseClicked

    private void fullImageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullImageLabelMouseClicked
        this.fullImageWindow.setVisible(false);
    }//GEN-LAST:event_fullImageLabelMouseClicked

    private void mainExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainExitButtonMouseClicked
        exitReader();
    }//GEN-LAST:event_mainExitButtonMouseClicked
    
    private void exitReader() {
        setVisible(false);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RFIDgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RFIDgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RFIDgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RFIDgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RFIDgui().setVisible(true);
            }
        });
    }

    private java.util.ArrayList<RFIDdata> rfidTagList = new java.util.ArrayList<RFIDdata>();
    private java.util.ArrayList<RFIDdata> writeTagList = new java.util.ArrayList<RFIDdata>();
    private java.util.ArrayList<RFIDdata> rfidTagDatabase = new java.util.ArrayList<RFIDdata>();
    private String databaseFile = "./database/default.json";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JScrollPane detectedTagScrollPanel;
    private javax.swing.JTable detectedTagTable;
    private javax.swing.JPanel editTagPanel;
    private javax.swing.JFrame editTagWindow;
    private javax.swing.JButton exitTagWindow;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenuQuit;
    private javax.swing.JLabel fullImageLabel;
    private javax.swing.JFrame fullImageWindow;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mainExitButton;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton scanButton;
    private javax.swing.JLabel thumbnailDisplay;
    private javax.swing.JButton viewFullSizeImage;
    // End of variables declaration//GEN-END:variables
}
